### PR TITLE
Update NPI file location to use new domain

### PR DESCRIPTION
**Pull request by dimfeld**

### CODE REVIEW

**Comment by dimfeld** [comment]
Here's the relevant news that spurred this change, in case you haven't seen it: http://nppes.viva-it.com/NPI_Files.html

**Comment by untoldone** [comment]
Thanks for the submission -- Looks like theres some more updates that'll be needed for the switch too .. e.g. https://github.com/gocodo/bloomnpi/blob/master/helpers/nppesFiles.go will need to have the page searched for files updated as well.

**Comment by dimfeld** [comment]
Ah, good call. It works for now since the filenames and dates are identical between the two sites, but we certainly don't want to rely on that. I'll submit an updated PR soon. Thanks!

**Comment by dimfeld** [comment]
Ok, I think that should do it. I didn't see anything beyond nppesFiles.go that also needed to be updated.

**Comment by untoldone** [comment]
Looks great, thanks!

**Comment by untoldone** [comment]
@dimfeld Just FYI so you can update your own branches if need be: the weekly regexp had a bug where it would only pick up the last weekly update in the list instead of all of them if bootstrapping from scratch. This has been fixed with a83a9a28074412696d18cad9265d17c2caf098ab

**Comment by dimfeld** [comment]
Ah, sorry about that. Thanks for the fix!

**Pull request merged**
